
name: Build iOS Distribution

on:
  push:
    tags: [ "release*" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: setup source
        id: build-release
        env:
          GMAP_APIKEY : ${{ secrets.GMAP_APIKEY }}
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          export PYTHONPATH='.'
      - name: Generate protobufs
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-osx-x86_64.zip
          unzip protoc-*.zip -d protoc
          export PATH="protoc/bin:$PATH"
          bin/gen-protos.sh
      - name: Create a distribution
        id: dist
        run: |
          pyinstaller --add-data 'lemon_pi/config/:lemon_pi/config' \
                      --onefile --windowed \
                      lemon_pi/pit/lemon-pi-pit.py

          tar cvfz lemon-pi-pit-ios.tar.gz dist/*
          rm -rf build/ dist/

      - id: upload-release
        if: steps.dist.outcome == 'success'
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          path: lemon-pi-pit-ios.tar.gz
          destination: perplexus/public/dist


